### ISSUE TITLE
Add examples based on ViT

### ISSUE THREAD

**Issue by dacorvo** [huggingface/optimum-quanto#169]
Vision Transformers should be supported out-of-the-box by `quanto`.

The goal of this issue is to add some examples under `examples/vision`.

At the very minimum, there should be a classification example, using a relatively small dataset so that people can rerun it locally without downloading gigabytes of images ([imagenette](https://huggingface.co/datasets/frgfm/imagenette) maybe ?).

An image detection example would also be nice if possible, but maybe it requires too much code.

**Comment by EduardoPach** [comment]
@dacorvo I can work on that. I've been contributing to the `transformers` library recently, but I also want to get into the `quanto` library as it seems pretty fun!

**Comment by mattiadg** [comment]
@dacorvo I would like to work on this

**Comment by dacorvo** [comment]
@mattiadg sure: feel free to select a model and create an example.

**Comment by mattiadg** [comment]
Oh but I see now there are already 3 examples under `vision`. Maybe we want to add something different, like Whisper for speech recognition?

**Comment by dacorvo** [comment]
@mattiadg yes a whisper example would be awesome

**Comment by shovan777** [comment]
@dacorvo I am working on adding a ViT example using the oxford Pets dataset. Is that a good classification example?

**Comment by dacorvo** [comment]
Nice ! Looking forward to see your example. When submitting your pull-request, please do not forget to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to make it easier to review.

**Comment by shovan777** [comment]
> Nice ! Looking forward to see your example. When submitting your pull-request, please do not forget to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to make it easier to review.

I made a [PR](https://github.com/huggingface/optimum-quanto/pull/308). 
But I couldn't perform model requantize as I faced a problem with `quantization_map` function. 
<img width="826" alt="Screenshot 2024-09-12 at 10 40 48" src="https://github.com/user-attachments/assets/dc42b615-71a0-4ff1-851f-91a41f7c75c3">
It seems the `QLayerNorm` doesn't have a quantization weight type. Is this a issue with `QLayerNorm`?

**Comment by dacorvo** [comment]
> It seems the `QLayerNorm` doesn't have a quantization weight type. Is this a issue with `QLayerNorm`?

Yes, line 168 should be modified to support `weight_qtype == None`, as the line below. If you don't mind, you could add a fix commit to your pull-request.

**Comment by shovan777** [comment]
Yes, I can do that. But do you think I should create a new PR for this or should I commit in the same [PR](https://github.com/huggingface/optimum-quanto/pull/308)?

**Comment by dacorvo** [comment]
Do it in the same pull-request, but in a separate commit. They are not squashed when merging so it will appear as a stand-alone change.

**Comment by shovan777** [comment]
> Do it in the same pull-request, but in a separate commit. They are not squashed when merging so it will appear as a stand-alone change.

I have made the change and committed. Is test case necessary for the change?
