### ISSUE TITLE
Why the quantized net is slower?

### ISSUE THREAD

**Issue by theguardsgod** [huggingface/optimum-quanto#184]
batch_size: 1, torch_dtype: fp32, unet_dtype: int8  in 3.754 seconds.
Memory: 5.240GB.

batch_size: 1, torch_dtype: fp32, unet_dtype: None  in 3.378 seconds.
Memory: 6.073GB.

I'm using the example code for stable diffusion, but the inference time is slower for quantized int8 version (I've also test the speed on my own model, and quantization brings larger VRAM and slower inference time). Why is that case?

**Comment by canamika27** [comment]
same observation

**Comment by newgrit1004** [comment]
same observation in NVIDIA A30
