### ISSUE TITLE
Switch to ruff native formatter

### ISSUE THREAD

**Issue by dacorvo** [huggingface/optimum-quanto#186]
Ruff is faster than black and produces nearly identical results.

The goal of this issue is to switch to ruff for the style check and formatting.

**Comment by aryanmagoon** [comment]
By switching to ruff for style check and formatting, do you mean removing black? It looks like both black and ruff run to do style check in workflows and as in the instructions for contributing, running `make style` formats with both packages.

**Comment by dacorvo** [comment]
> > Yes, it means removing black and use only ruff.
> 
> Dear optimum-quanto maintainers, I saw black is still in the setup.sh and pyproject.toml, are we still considering switching?

Yes, this is still planned, but no pull-request has been submitted yet.

**Comment by ishandeva** [comment]
@dacorvo Submitted a pull request for this, please review and let me know.
Thanks.

**Comment by dacorvo** [comment]
Done in #334
