### ISSUE TITLE
CUDA Kernel

### ISSUE THREAD

**Issue by satabios** [huggingface/optimum-quanto#214]
I see that upon quantization, that kernel run on W8A8 however, I'm unable to find how it is implemented? Can you point where to find these implementations?

Thanks in advance.

**Comment by dacorvo** [comment]
https://github.com/huggingface/optimum-quanto/blob/71692d5f63a8a966dfe3da493d34cf0ba65e89b5/optimum/quanto/tensor/qbytes_ops.py#L215
