### ISSUE TITLE
Should we stop using quanto without the optimum?

### ISSUE THREAD

**Issue by kechan** [huggingface/optimum-quanto#215]
Is this going to replace this?

from quanto import Calibration, freeze, qfloat8, qint4, qint8, quantize

and from this point, we should 

from optimum.quanto import Calibration, freeze, qfloat8, qint4, qint8, quantize

Is the "old" quanto not going to be supported?

**Comment by dacorvo** [comment]
@kechan you're right, the "old" quanto is not going to be supported anymore. All future releases will be optimum-quanto.
