### ISSUE TITLE
why missing ?

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/optimum-quanto#224]
site-packages\quanto\library\ops.py:66: UserWarning: An exception was raised while calling the optimized kernel for quanto::dqmm: DLL load failed while importing quanto_cpp: The specified module could not be found. Falling back to default implementation.                                 
  warnings.warn(message + " Falling back to default implementation.")

**Comment by dacorvo** [comment]
This legacy kernel has been removed. Can you try with the latest version of `optimum-quanto` ?
