### ISSUE TITLE
Integrate marlin fp16/bf16-int4/int8 matrix multiplication kernel

### ISSUE THREAD

**Issue by dacorvo** [huggingface/optimum-quanto#239]
Since the introduction of mixed-precision fp16-int4 [MARLIN](https://github.com/IST-DASLab/marlin) (Mixed Auto-Regressive Linear) kernels by IST-DASLab, new mixed-precision MARLIN kernels have been introduced for other data types.

In particular, mixed-precision fp16/bf16-int4/int8 kernels have been [contributed to TGI](https://github.com/huggingface/text-generation-inference/pull/2052) and could be integrated in `optimum-quanto` as well with companion `Int8MarlinQBytesTensor` and `Int4MarlinQBitsTensor` to pack the weights.

**Comment by dacorvo** [comment]
The kernel has been integrated in quanto CUDA extension in https://github.com/huggingface/optimum-quanto/tree/add_marlin_int4_kernel (thanks @shcho1118).
It needs now to be fully integrated at inference.

**Comment by shovan777** [comment]
@dacorvo what should be done to integrate this at inference?

**Comment by dacorvo** [comment]
What is missing is a `MarlinWeightsQBitsTensor` class in the same spirit as `AWQBitsTensor` class, and a modification to `QBitsTensor.create` to select that class instead of AWQBitsTensor (because this kernel is more stable).
This is a bit involved as you have to do things right to stay compatible with serialization, gradients and compilation (all things done already in `AWQBitsTensor`).
Also, this requires writing some tests.

**Comment by dacorvo** [comment]
Done in #333
