### ISSUE TITLE
is textencoder Quantized Diffusers models can be saved and loaded?

### ISSUE THREAD

**Issue by lonngxiang** [huggingface/optimum-quanto#264]

**Comment by sayakpaul** [comment]
They can be. Follow this: https://github.com/huggingface/optimum-quanto?tab=readme-ov-file#llm-models

For the unimplemented classes, you can just refer to https://github.com/huggingface/optimum-quanto/blob/601dc193ce0ed381c479fde54a81ba546bdf64d1/optimum/quanto/models/transformers_models.py#L171

And send us a PR.

**Comment by lonngxiang** [comment]
> They can be. Follow this: https://github.com/huggingface/optimum-quanto?tab=readme-ov-file#llm-models
> 
> For the unimplemented classes, you can just refer to
> 
> https://github.com/huggingface/optimum-quanto/blob/601dc193ce0ed381c479fde54a81ba546bdf64d1/optimum/quanto/models/transformers_models.py#L171
> 
> And send us a PR.

how PixArt-alpha/PixArt-Sigma-XL-2-1024-MS model use save and  load text  Quantized model

**Comment by Ednaordinary** [comment]
> > They can be. Follow this: https://github.com/huggingface/optimum-quanto?tab=readme-ov-file#llm-models
> > For the unimplemented classes, you can just refer to
> > https://github.com/huggingface/optimum-quanto/blob/601dc193ce0ed381c479fde54a81ba546bdf64d1/optimum/quanto/models/transformers_models.py#L171
> > 
> > And send us a PR.
> 
> how PixArt-alpha/PixArt-Sigma-XL-2-1024-MS model use save and load text Quantized model

This is shown in the guide
https://huggingface.co/blog/quanto-diffusers
![image](https://github.com/user-attachments/assets/280a32d3-f7e5-4b38-98e8-be95274b4eea)

**Comment by Ednaordinary** [comment]
Also, @sayakpaul, is there a way to load models without entirely requantizing them? I'm trying to load flux from a quantized save (made a class), but it takes a while due to the requantization (I think), to the point where there's no real reason to not just load normally and quantize on the fly
![image](https://github.com/user-attachments/assets/54de018c-a2c3-4fe3-8650-626658a239e1)

**Comment by sayakpaul** [comment]
Will let @dacorvo comment on that. But he is on vacation so expect delay.

**Comment by dacorvo** [comment]
@Ednaordinary some recent pull-requests might have fixed the long requantization times (see #290).

**Comment by Ednaordinary** [comment]
@dacorvo Nice! Something along the way must have also changed how the first move between devices works because I'm seeing a lot faster transfer between CPU and GPU on the first move. Thanks for your hard work!

**Comment by dacorvo** [comment]
> Something along the way must have also changed how the first move between devices works because I'm seeing a lot faster transfer between CPU and GPU on the first move.

This must be #291.

> Thanks for your hard work!

Kudos to @latentCall145 !
