### ISSUE TITLE
Support for new diffuser: flux1.schnell

### ISSUE THREAD

**Issue by KoppAlexander** [huggingface/optimum-quanto#272]
@sayakpaul

Hello,

I am looking for support for saving and loading the flux1.schnell model from Blackforest.

Following your code from the "Bonus" [here](https://github.com/huggingface/blog/blob/main/quanto-diffusers.md#bonus---saving-and-loading-diffusers-models-in-quanto)

Saving
```
from diffusers import PixArtTransformer2DModel
from optimum.quanto import QuantizedPixArtTransformer2DModel, qfloat8

model = PixArtTransformer2DModel.from_pretrained("PixArt-alpha/PixArt-Sigma-XL-2-1024-MS", subfolder="transformer")
qmodel = QuantizedPixArtTransformer2DModel.quantize(model, weights=qfloat8)
qmodel.save_pretrained("pixart-sigma-fp8")
```
Loading
```
from optimum.quanto import QuantizedPixArtTransformer2DModel
import torch

transformer = QuantizedPixArtTransformer2DModel.from_pretrained("pixart-sigma-fp8") 
transformer.to(device="cuda", dtype=torch.float16)
```

I am looking for a similar option to save and load the two quantized models in this repo [here](https://gist.github.com/VvanGemert/ab9c3ce63f12d429cf6075dbd764e57c), 

see line 38,45,46 
```
transformer = FluxTransformer2DModel.from_pretrained(bfl_repo, subfolder="transformer", torch_dtype=dtype, revision=revision)
quantize(transformer, weights=qfloat8)
freeze(transformer)
```
and 35,48,49.
```
text_encoder_2 = T5EncoderModel.from_pretrained(bfl_repo, subfolder="text_encoder_2", torch_dtype=dtype, revision=revision)
quantize(text_encoder_2, weights=qfloat8)
freeze(text_encoder_2)
```
If I'm correctly understanding this, there would need to be somethin like 

`from optimum.quanto import QuantizedFluxTransformer2DModel` for the transformer
and
`from optimum.quanto import T5EncoderModel` for the text_encoder_2
to be able to save and load the quantized models for the transformer and encoder. Is that correct? Or is tehre another possibility which avoids importing the quantized version of a model from optimum.quanto?

Thank you!

@sayakpaul

**Comment by KoppAlexander** [comment]
Thanks for the quick answer!

Did it like this:

~~~
class QuantizedFlux2DModel(QuantizedDiffusersModel):
    base_class = FluxTransformer2DModel

class QuantizedT5Model(QuantizedTransformersModel):
    auto_class = T5EncoderModel
~~~

Do you know if that's the correct way to use it? Or is an additional freeze step necessary between quantization and saving?

~~~
# quantizing
print("start loading transformer...")
transformer = FluxTransformer2DModel.from_pretrained(bfl_repo, subfolder="transformer", torch_dtype=dtype)#, revision=revision)
print("start quantizing...")
qtransformer = QuantizedFlux2DModel.quantize(transformer, weights=qint4, exclude=["proj_out", "x_embedder", "norm_out", "context_embedder"])
print("...end quantizing")

# NECESSARY?
freeze(qtransformer)

# saving
print("start saving...")
qtransformer.save_pretrained(f"{bfl_repo}/q_transformer")
print("...end saving")

# loading
qtransformer = QuantizedFlux2DModel.from_pretrained(f"{bfl_repo}/q_transformer")
qtransformer.to(device="cpu", dtype=dtype)
~~~

**Comment by sayakpaul** [comment]
After you quantize, it's not necessary to freeze as you can see it happens within the `quantize()` call:

https://github.com/huggingface/optimum-quanto/blob/601dc193ce0ed381c479fde54a81ba546bdf64d1/optimum/quanto/models/diffusers_models.py#L114

Rest looks good to me.
