### ISSUE TITLE
NF4/bitsandbytes support for flux.dev and flux.schnell

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [huggingface/optimum-quanto#277]
It is talked about here:

https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981

According to the author:

> (i) NF4 is significantly faster than FP8. For GPUs with 6GB/8GB VRAM, the speed-up is about 1.3x to 2.5x (pytorch 2.4, cuda 12.4) or about 1.3x to 4x (pytorch 2.1, cuda 12.1). I test 3070 ti laptop (8GB VRAM) just now, the FP8 is 8.3 seconds per iteration; NF4 is 2.15 seconds per iteration (in my case, 3.86x faster). This is because NF4 uses native bnb.matmul_4bit rather than torch.nn.functional.linear: casts are avoided and computation is done with many low-bit cuda tricks. (Update 1: bnb's speed-up is less salient on pytorch 2.4, cuda 12.4. Newer pytorch may used improved fp8 cast.) (Update 2: the above number is not benchmark - I just tested very few devices. Some other devices may have different performances.) (Update 3: I just tested more devices now and the speed-up is somewhat random but I always see speed-ups - I will give more reliable numbers later!)
>
>(ii) NF4 weights are about half size of FP8.
>
>(iii) NF4 may outperform FP8 (e4m3fn/e5m2) in numerical precision, and it does outperform e4m3fn/e5m2 in many (in fact, most) cases/benchmarks.
>
>(iv) NF4 is technically granted to outperform FP8 (e4m3fn/e5m2) in dynamic range in 100% cases.
>
>This is because FP8 just converts each tensor to FP8, while NF4 is a sophisticated method to convert each tensor to a combination of multiple tensors with float32, float16, uint8, int4 formats to achieve maximized approximation.
>
> (Do not confuse FP8 with bnb-int8! In large language models, when people say "8-bits better than 4 bits", they are (mostly) talking about bnb’s 8-bit implementation, which is a more sophisticated method that also involve storing [chunked float32 min/max norms](https://github.com/bitsandbytes-foundation/bitsandbytes/blob/6d714a5cce3db5bd7f577bc447becc7a92d5ccc7/bitsandbytes/nn/modules.py#L594). The fp8 here refers to the naked e4m3fn/e5m2 without extra norms. ) <- You can say that bnb-8bit is more precise than nf4. But e4m3fn/e5m2 may not.

**Comment by lonngxiang** [comment]
same demand
