### ISSUE TITLE
Does AWQ is officially supported now?

### ISSUE THREAD

**Issue by lifelongeeek** [huggingface/optimum-quanto#313]
I can see that optimum-quanto provides several external (weight-only) quantization algorithm such as smoothquant and awq in [here](https://github.com/huggingface/optimum-quanto/tree/main/external).

It looks like smoothquant only supports OPT models, and awq is still under development. Do you have any further development plans for AWQ?

**Comment by lifelongeeek** [comment]
Oh I notice that optimum-quanto offer HQQ, calibration data-free quantization algorithm and achieves [fairly good perplexity with Shared-llama-1.3B](https://github.com/huggingface/optimum-quanto/pull/128#issue-2200332038). Does HQQ optimizer officially supported now?

**Comment by dacorvo** [comment]
HQQ and AWQ both use the same group-wise quantization scheme introduced by GPTQ. They only differ from the original GPTQ algorithm in the way they select the scale and adjust the weights (PTQ = Post-Training-Quantization).
Quanto uses a similar algorithm so it is strictly equivalent to these methods, although AWQ PTQ is not implemented.

If you plan to reuse existing HQQ or AWQ weights they have sadly chosen in their implementations to store the quantized weights in different formats that quanto can't load at the moment, although it includes packing/unpacking code compatible with AWQ weights (so it should be fairly easy to write a conversion script).

**Comment by lifelongeeek** [comment]
Thanks for the detail explanation. 

> although it includes packing/unpacking code compatible with AWQ weights (so it should be fairly easy to write a conversion script).

Could you inform us any relevant reference docs or code? I am interested in this direction.
