### ISSUE TITLE
Do the Linear layers quantized with W8A8 include output quantization layers?

### ISSUE THREAD

**Issue by chenghuaWang** [huggingface/optimum-quanto#324]
I used the code in `examples/nlp/text-generation/quantize_causal_lm_model.py` to quantize the Qwen LLM model. I used a quantization setting of Weight=qint8, Activation=qint8.

I printed the structure of one of the layers, and it is displayed as follows:

```text
Layer Name: model.layers.19.self_attn
Layer: Qwen2SdpaAttention(
  (q_proj): QLinear(in_features=1024, out_features=1024, bias=True)
  (k_proj): QLinear(in_features=1024, out_features=1024, bias=True)
  (v_proj): QLinear(in_features=1024, out_features=1024, bias=True)
  (o_proj): QLinear(in_features=1024, out_features=1024, bias=False)
  (rotary_emb): Qwen2RotaryEmbedding()
)
```

If I understand correctly, QLinear accepts int8 `X`, int8 `Weight`, and fp16 `Bias`, with the output being fp16. Since I used Activation=qint8, when is the fp16 output converted to int8? I didn't find any layers similar to Quantize and DeQuantize in the layer I printed out.

**Comment by dacorvo** [comment]
https://github.com/huggingface/optimum-quanto/blob/5f88400baec561a79cdb87311608981c17e4c368/optimum/quanto/nn/qmodule.py#L290

But be aware that when calibrating activations, `streamline` is true by default, which most of the time disables output quantization because the operation following the linear operation is not compatible.

**Comment by chenghuaWang** [comment]
Thank you for your answer. You mean that during the calibrating activations, the output is likely not quantized. So, during the inference stage, it is all quantized, right?

I have another question. I use the following API to save the file:

```python
model.save_pretrained('./Qwen1.5-0.5B-Chat-w8a8')
```

What flag should I add to enable the model to save the output_scale of Activations?

I found this: [https://github.com/huggingface/optimum-quanto/blob/5f88400baec561a79cdb87311608981c17e4c368/optimum/quanto/nn/qmodule.py#L146](https://github.com/huggingface/optimum-quanto/blob/5f88400baec561a79cdb87311608981c17e4c368/optimum/quanto/nn/qmodule.py#L146) where there is a `keep_vars` flag. However, it seems that `save_pretrained` does not accept this flag.

**Comment by dacorvo** [comment]
> Thank you for your answer. You mean that during the calibrating activations, the output is likely not quantized. So, during the inference stage, it is all quantized, right?

No, unless you set explicitly streamline=False during calibration.

> I have another question. I use the following API to save the file:
> 
> ```python
> model.save_pretrained('./Qwen1.5-0.5B-Chat-w8a8')
> ```

To save transformers model, use the `QuantizedModelForCausalLM` class, as specified in https://github.com/huggingface/optimum-quanto#llm-models.

**Comment by dacorvo** [comment]
The `quantize_model_for_causal_lm` example should be updated to use that class, actually.

**Comment by chenghuaWang** [comment]
> No, unless you set explicitly streamline=False during calibration.

Thank you, I've got it.

> To save transformers model, use the QuantizedModelForCausalLM class, as specified in https://github.com/huggingface/optimum-quanto#llm-models.

Does the `save_pretrained` function in `QuantizedModelForCausalLM` class will save "input_scale" and "output_scale"? If I use `QuantizedModelForCausalLM`, how should I perform calibration?

**Comment by chenghuaWang** [comment]
I'm not familiar with quanto. Could you please provide some insights as to why the `input_scale` and `output_scale` parameters are not being saved using the `save_pretrained` method?

If the `input_scale` and `output_scale` parameters are not saved, it implies that calibration would need to be performed each time the model is loaded, which can be inefficient.
```python
    def _save_to_state_dict(self, destination, prefix, keep_vars):
        if self.weight_qtype is None or not self.frozen:
            # Save standard weight Tensor
            destination[prefix + "weight"] = self.weight if keep_vars else self.weight.detach()
        else:
            # Save QTensor using dedicated method
            self.weight.save_to_state_dict(destination, prefix + "weight.", keep_vars)
        if self.bias is not None:
            destination[prefix + "bias"] = self.bias if keep_vars else self.bias.detach()
        destination[prefix + "input_scale"] = self.input_scale if keep_vars else self.input_scale.detach()
        destination[prefix + "output_scale"] = self.output_scale if keep_vars else self.output_scale.detach()
```

**Comment by dacorvo** [comment]
They are saved in the state_dict, as you can see in the code snippet.

**Comment by chenghuaWang** [comment]
Thank you! I found that I made a mistake when printing the parameters, which made these scale parameters not printed. :rofl:

**Comment by chenghuaWang** [comment]
Thank you! I found that I made a mistake when printing the parameters, which made these scale parameters not printed. :rofl:
