### ISSUE TITLE
Will module output not be quantized when the model is directly trained after Calibration?

### ISSUE THREAD

**Issue by tusiqi1** [huggingface/optimum-quanto#336]

**Comment by tusiqi1** [comment]
1. model structure and train data is:
![image](https://github.com/user-attachments/assets/e88e2cd6-2d9a-4588-9884-074a5da575db)
2. clibration code is:
![image](https://github.com/user-attachments/assets/56ab2648-c81e-4f20-ae14-d48fa6181930)
3. train quant model with initial input_scale and output_scale code is:
![image](https://github.com/user-attachments/assets/0562aafb-1147-4de7-8312-5c85f0bb1e47)

I found that when I executed step 3, the output quant would not execute, and the reason is: 
![image](https://github.com/user-attachments/assets/73c95b6b-869c-4a51-a9b7-344a06d2d36f)

Why should the code in the red box disable output quant?

**Comment by tusiqi1** [comment]
> As you can see in the comment on the line you highlighted, the quantization of the outputs is disabled because the operation immediately following is not compatible with quantized inputs. This means that when the Tensor reaches that operation, it will be immediately dequantized: the `streamline` optimization policy removes the spurious `quantize`/`dequantize`.
> 
> If you want to disable this behaviour, just pass `streamline=False` during calibration.


![image](https://github.com/user-attachments/assets/103adb7f-bc86-4375-b4cc-d89430ed7cab)
When I press the break point in the image above, the entire model is passed to the calibrate_output() function, which causes the quantization of the output to be turned off. 

Is this right?

**Comment by dacorvo** [comment]
Just use with `Calibration(streamline=False):` to disable this behaviour.

**Comment by tusiqi1** [comment]
> Just use `with Calibration(streamline=False):` to disable this behaviour.

Thank you very much, I'll think more about the purpose of streamline myself.
