### ISSUE TITLE
Error when quantizing flux (already fixed in master)

### ISSUE THREAD

**Issue by samedii** [huggingface/optimum-quanto#339]
Seeing this for both qint8 and qint4 for flux. I saw that it was fixed in master. Would be nice if you could do a release with the fix :)

```
.venv/lib/python3.10/site-packages/optimum/quanto/tensor/weights/ti
nygemm/qbits.py", line 52, in forward     
    input.view(-1, in_features), other._data._data, other._group_size, other._scale_shift
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension
 spans across two contiguous subspaces). Use .reshape(...) instead.
 ```
 
 (It's another trace for qint8 of course but it was also fixed.)

**Comment by dacorvo** [comment]
It should indeed be fixed in [0.2.6](https://github.com/huggingface/optimum-quanto/releases/tag/v0.2.6)
