### ISSUE TITLE
Inference Speed Slowdown with Static Quantization

### ISSUE THREAD

**Issue by ClaraLovesFunk** [huggingface/optimum-quanto#340]
Hey folks,

I ran your example file for static quantization using distilbert-base-uncased-finetuned-sst-2-english on the dataset "sst2". The quantized model was 90 % faster than the single precision model. When I applied quantization accordingly to my own self-finetuned model PubMedBERT on my own customized relation extraction dataset, inference was 50 % Slower. Also I could not use higher batch sizes for the quantized model which made me suspicious that quantization was not successfully applied to my model. 

Do you have any explaination for that or leads how to apply quantization successfully (leading to inference speed improvement)?

Cheers from Berlin
Clara

**Comment by dacorvo** [comment]
@ClaraLovesFunk thank you for your feedback.
The inference speed of a quantized model greatly depends on the availability of optimized fused operations (aka kernels) for processing quantized tensors. And of course, the model must be frozen (otherwise quantization is applied dynamically), and in eval mode.
Can you share a code snippet on how you quantized your model ?

**Comment by ClaraLovesFunk** [comment]
Hi @dacorvo, thank you so much for your swift reply! I finally fixed my code and finalized my experiments.

I ran my fine-tuned model pubmedbert (Huggingface path: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract") on my dataset Drugprot on an A100.

Observations:
- Inference time decreased by 50 %
- Batchsize the model was able to process remained the same

Question:
- I'd assume that optimized fused operations are available, since PubMedBERT is BERT pre-trained on different data. Do you have an idea why the speedup is not higher? With half-precision I reach a speedup of 5 times.
- Do you have an idea, why I cannot process higher batch sizes as opposed to the single-precision model? I ensured VRAM is cleared before running my quantized model.
- Do you have a hypothesis, why my model is much slower when I reload my quantized model vs. when I callibrate, quantize and use the model directly?

I add the code snippets below.

Thank you so much for your help!
Cheers 
Clara


Code Snippet:

def evaluate_model(model, dataset, device, batch_size):

    model.eval() #### auf model.train

    dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size)

    predictions = []
    total_inference_time = 0

    use_autocast = model.dtype in [torch.float16, torch.bfloat16]

    for batch in dataloader:
        inputs = {k: v.to(device) for k, v in batch.items() if k in ['input_ids', 'attention_mask']}
        with torch.no_grad(), torch.cuda.amp.autocast(enabled=use_autocast):

            start_event = torch.cuda.Event(enable_timing=True)
            end_event = torch.cuda.Event(enable_timing=True)

            start_event.record()
            outputs = model(**inputs)
            preds = torch.argmax(outputs.logits, dim=-1)
            end_event.record()

            torch.cuda.synchronize()
            inference_time = start_event.elapsed_time(end_event) / 1000
            total_inference_time += inference_time

            for idx, pred in enumerate(preds):
                predictions.append({
                    'sample_id': batch['sample_id'][idx],
                    'document_id': batch['document_id'][idx],
                    'Arg1': batch['arg1'][idx],
                    'Arg2': batch['arg2'][idx],
                    'pred_label': id2label[pred.item()]
                })

            del start_event, end_event

    return predictions, total_inference_time

EXP_ID = 'quantization_int8_int8_reloaded'

weights = qint8
activations = qint8

print(f"(VRAM): {torch.cuda.memory_allocated() / 1024**2:.2f} MB")
model_quantized_reloaded = AutoModelForSequenceClassification.from_pretrained(model_path, num_labels=len(label_mapping)).to(device)
print(f"(VRAM): {torch.cuda.memory_allocated() / 1024**2:.2f} MB")
quantize(model_quantized_reloaded, weights=weights, activations=activations)
print(f"(VRAM): {torch.cuda.memory_allocated() / 1024**2:.2f} MB")
state_dict = torch.load(model_quantized_path)
model_quantized_reloaded.load_state_dict(state_dict)
print(f"(VRAM): {torch.cuda.memory_allocated() / 1024**2:.2f} MB")

for BATCH_SIZE in BATCH_SIZE_ALL:
    try:
      predictions_quantized_reloaded, time_quantized_reloaded = evaluate_model(model_quantized_reloaded, dataset, device, BATCH_SIZE)
      print(time_quantized_reloaded)
      save_res(res_dir, res_file_names, EXP_ID=EXP_ID, BATCH_SIZE=BATCH_SIZE, predictions=predictions_quantized_reloaded, time=time_quantized_reloaded)
    except Exception as e:
        print(f"Miep, {BATCH_SIZE} was too big: {e}")
        continue

del model_quantized_reloaded
torch.cuda.empty_cache()
print(f"(VRAM): {torch.cuda.memory_allocated() / 1024**2:.2f} MB")

Output:

(VRAM): 0.00 MB
(VRAM): 413.44 MB
(VRAM): 413.53 MB
<ipython-input-9-1f17e2ca57b4>:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(model_quantized_path)
(VRAM): 255.87 MB
<ipython-input-8-2d024fff5229>:14: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.no_grad(), torch.cuda.amp.autocast(enabled=use_autocast):
24.08348635101317
22.39302304077149
22.039412536621093
21.886560729980467
21.821751098632813
21.791343994140625
Miep, 4096 was too big: CUDA out of memory. Tried to allocate 12.00 GiB. GPU 0 has a total capacity of 39.56 GiB of which 11.75 GiB is free. Process 27364 has 27.81 GiB memory in use. Of the allocated memory 26.77 GiB is allocated by PyTorch, and 558.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Miep, 8192 was too big: CUDA out of memory. Tried to allocate 24.00 GiB. GPU 0 has a total capacity of 39.56 GiB of which 7.25 GiB is free. Process 27364 has 32.31 GiB memory in use. Of the allocated memory 29.29 GiB is allocated by PyTorch, and 2.53 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Miep, 16384 was too big: CUDA out of memory. Tried to allocate 8.90 GiB. GPU 0 has a total capacity of 39.56 GiB of which 4.34 GiB is free. Process 27364 has 35.21 GiB memory in use. Of the allocated memory 27.02 GiB is allocated by PyTorch, and 7.71 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
(VRAM): 263.99 MB
