### ISSUE TITLE
QuantizedModelForCausalLM lost repr, cannot see model structure

### ISSUE THREAD

**Issue by imba-tjd** [huggingface/optimum-quanto#355]
![图片](https://github.com/user-attachments/assets/2f6e54a3-baa3-44bf-a947-dea64bbad3e7)

---

![图片](https://github.com/user-attachments/assets/f3300194-1fb9-4f1e-8180-929bc5a79c4e)

Is this intentional?

**Comment by dacorvo** [comment]
The repr method is indeed not implemented for this class. It shouldn't be too difficult to add it, calling the inner model repr.
